name       : apcupsd
version    : 3.14.14
release    : 2
source     :
    - https://downloads.sourceforge.net/project/apcupsd/apcupsd - Stable/3.14.14/apcupsd-3.14.14.tar.gz : db7748559b6b4c3784f9856561ef6ac6199ef7bd019b3edcd7e0a647bf8f9867
license    : GPL-2.0-only
component  : system.util
summary    : APC UPS Daemon can be used for powermanagement and controlling most of APC's UPS models.
description: |
    - APC UPS Daemon can be used for powermanagement and controlling most of APC's UPS models.
builddeps  :
    - pkgconfig(libnih)
rundeps    :
    - libnih
setup      : |
    %configure --enable-usb --enable-snmp
build      : |
    %make
install    : |
    %make_install
